title: Blake Simpson # your name (or website title) here
logo: "/images/BlakeSimpson.jpg?raw=true"
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  Statistics graduate with a strong foundation in R, SQL, and Python, and hands-on experience in data cleaning, exploratory data analysis, and applied machine learning.
  <br><br>
  <a href="https://www.linkedin.com/in/blake-simpson-0034b5351/">View my LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal

colors:
  crimson: '#900C3F'
